commit of crud
jainis2001/JDBCManagement pull request #1
Opened 2023-03-29 05:20 UTC by jainis2001

implemented crud

2023-04-03 11:13 UTC, tnahddisttud requested changes

2023-04-03 11:13 UTC, tnahddisttud commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/mysql/mysql-connector-java -->
Remove comment and unwanted blank lines

2023-04-03 11:13 UTC, tnahddisttud commented on src/main/java/org/example/repo/AddressDaoImpl.java
> +			PreparedStatement pstmt=con.prepareStatement("select addressid from address where landmark=? and pincode=?");
Save query strings s constants, don't pass raw string values.

2023-04-03 11:13 UTC, tnahddisttud commented on src/main/java/org/example/repo/AddressDaoImpl.java
> +			PreparedStatement pStmtAddress=con.prepareStatement("insert into address(addressid,landmark,city,state,pincode) values(?,?,?,?,?)");
Save query strings as constants, don't pass raw string values.

2023-04-03 11:13 UTC, tnahddisttud commented on src/main/java/org/example/repo/AddressDaoImpl.java
> +			String query="update address set landmark=?,pincode=?,city=?,state=? where addressid=?";
Save query strings as constants, don't pass raw string values.

2023-04-03 11:13 UTC, tnahddisttud commented on src/main/java/org/example/repo/StudentDaoImpl.java
> +			PreparedStatement pstmt=con.prepareStatement("select studentid from tempstudent where email=? and firstname=? and lastname=? and studentid<>?");
Save query strings s constants, don't pass raw string values.

2023-04-03 11:13 UTC, tnahddisttud commented on src/main/java/org/example/repo/StudentDaoImpl.java
> +			PreparedStatement pstmt=con.prepareStatement("select studentid from tempstudent where email=? and firstname=? and lastname=?");
Save query strings s constants, don't pass raw string values.

2023-04-03 11:13 UTC, tnahddisttud commented on src/main/java/org/example/repo/StudentDaoImpl.java
> +			PreparedStatement pStmtStudent=con.prepareStatement("insert into tempstudent(studentid,firstName,lastName,age,mobile,email,gender,addressid) values(?,?,?,?,?,?,?,?)");
Save query strings s constants, don't pass raw string values.

2023-04-03 11:13 UTC, tnahddisttud commented on src/main/java/org/example/repo/StudentDaoImpl.java
> +			String query="update tempstudent set firstName=?,lastName=?,email=?,mobile=?,age=?,gender=?,addressId=? where studentid=?";
Save query strings s constants, don't pass raw string values.

2023-04-03 11:13 UTC, tnahddisttud commented on src/main/java/org/example/repo/StudentDaoImpl.java
> +			PreparedStatement pstmt=con.prepareStatement("delete from tempstudent where studentid=?");
Save query strings s constants, don't pass raw string values.

2023-04-03 11:13 UTC, tnahddisttud commented on src/main/java/org/example/repo/StudentDaoImpl.java
> +		String query="select studentid,age,mobile,firstName,lastName,email,gender,addressid from tempstudent";
Save query strings s constants, don't pass raw string values.

2023-04-03 11:13 UTC, tnahddisttud commented on src/main/java/org/example/repo/StudentDaoImpl.java
> +			String query="select studentid,age,mobile,firstName,lastName,email,gender,addressid from tempstudent where tempstudent.studentid=?";
Save query strings s constants, don't pass raw string values.

2023-04-03 11:13 UTC, tnahddisttud commented on src/main/java/org/example/controller/Main.java
> +			int ch;
Please follow proper naming conventions. `ch` isn't really intuitive in communicating the context of it's usage here

2023-04-03 11:13 UTC, tnahddisttud commented on src/main/java/org/example/controller/Main.java
> +				System.out.println("\n1: Insertion");
The `souts` can be extracted into a separate util method. Please try to reduce the complexity of the `main` method.

2023-04-03 11:13 UTC, tnahddisttud commented on src/main/java/org/example/controller/Main.java
> +						StudentDTO studentDTO = studentInfo.getInput();
Again, whatever logic is present inside the cases should be present in a separate method! Please take care of this in all the cases, wherever it makes sense.

2023-04-03 11:13 UTC, tnahddisttud commented on src/main/java/org/example/controller/Main.java
> +			System.out.println("Enter again");
Please communicate what went wrong in case of an error. The user should know why the error occurred if it did.

2023-04-03 11:13 UTC, tnahddisttud commented on src/main/java/org/example/controller/StudentInfo.java
> +	String firstName,lastName,email,gender,studentId;
I think it makes sense to have these as the local variables of `getInput` method. Thoughts? What do you think?

2023-04-03 11:13 UTC, tnahddisttud commented on src/main/java/org/example/repo/StudentDaoImpl.java
> +	public String isStuentExist(Student student) {
Why do we have `isStuentExist` and `isStuentExistForEdit`, as they're doing the same thing? Can we not have a single method for this? Please try to reduce code duplication,

2023-04-03 11:13 UTC, tnahddisttud commented on src/main/java/org/example/service/StudentServiceImpl.java
> +			student=new Student(studentDTO.getStudentId(),studentDTO.getFirstName(), studentDTO.getLastName(), studentDTO.getEmail());
Again, this code is duplicated from `isStudentExist`.

2023-04-03 11:13 UTC, tnahddisttud commented on src/main/java/org/example/service/StudentServiceImpl.java
> +			for(Student student:studentsRecord){
Can we use streams for this?

2023-04-03 12:20 UTC, jainis2001 commented on src/main/java/org/example/repo/StudentDaoImpl.java
> +	public String isStuentExist(Student student) {
actually both functions querys are different

isStuentExist(Student student){
  where email=? and firstname=? and lastname=?"
}

isStuentExistForEdit(Student student)
{
 "where email=? and firstname=? and lastname=? and studentid<>?"
// this function has studentid column
}

2023-04-03 12:42 UTC, tnahddisttud commented on src/main/java/org/example/repo/StudentDaoImpl.java
> +	public String isStuentExist(Student student) {
This is just one difference present in both methods, everything else is the same. Can we not add an `isUpdate` flag in the method signature and execute either of the statements based on that?

2023-04-04 05:26 UTC, tnahddisttud requested changes

2023-04-04 05:26 UTC, tnahddisttud commented on src/main/java/org/example/controller/Menu.java
> +				System.out.println("\n1: Insertion");
souts can be in a `displayOptions` method

2023-04-04 05:26 UTC, tnahddisttud commented on src/main/java/org/example/controller/StudentInfo.java
> +		String firstName,lastName,email,gender,studentId;
Didn't mean this when I asked you to make a local variable of the method. How about this?
`String studentId= util.createId();`

2023-04-04 05:26 UTC, tnahddisttud commented on src/main/java/org/example/repo/Queries.java
> +	public static final String studentExist="select studentid from tempstudent where email=? and firstname=? and lastname=?";
Follow naming conventions for Constants, `studentExist` ---> `STUDENT_EXISTS`

2023-04-04 05:26 UTC, tnahddisttud commented on src/main/java/org/example/service/StudentServiceImpl.java
> +								.filter(address -> address.getAddressId().equals(student.getAddressId())).findFirst().get();
What if the Optional is Empty?

2023-04-04 05:26 UTC, tnahddisttud commented on src/main/java/org/example/util/DBConnection.java
> +			con= DriverManager.getConnection("jdbc:mysql:///crudofjdbc","root","Patel67&");
_**DO NOT USE RAW STRINGS.**_

2023-04-04 10:32 UTC, jainis2001 commented on src/main/java/org/example/service/StudentServiceImpl.java
> +								.filter(address -> address.getAddressId().equals(student.getAddressId())).findFirst().get();
sir, in our scenario student address would never be empty (because for every student one address would be present) 
so Optional will never be empty

2023-04-05 05:59 UTC, tnahddisttud approved these changes
You may merge this into main

2023-04-05 06:16 UTC, merged